import {IProcess} from "../interfaces/ProcessRequest.ts";

export const processesData: IProcess[] =
    [
        {
            "id": 1,
            "operation": "94+46",
            "TEM": 17,
            "elapsdT": 0,
            "is_finished": false,
            "time_finished": 0,
            "remaining_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "initial_time": 0,
            "wait_time":0,
            "service_time":0,
            "return_time": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
        },
        {
            "TEM": 12,
            "elapsdT": 0,
            "id": 2,
            "initial_time": 0,
            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "98/66",
            "remaining_time_blocked": 0,
            "remaining_time_running": 12,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 17,
            "elapsdT": 0,
            "id": 3,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "23-33",
            "remaining_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 5,
            "elapsdT": 0,
            "id": 4,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "85+88",
            "remaining_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 9,
            "elapsdT": 0,
            "id": 5,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "73%73",
            "remaining_time_blocked": 0,
            "remaining_time_running": 9,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 12,
            "elapsdT": 0,
            "id": 6,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "75*66",
            "remaining_time_blocked": 0,
            "remaining_time_running": 12,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 14,
            "elapsdT": 0,
            "id": 7,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "11+41",
            "remaining_time_blocked": 0,
            "remaining_time_running": 14,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 15,
            "elapsdT": 0,
            "id": 8,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "82-66",
            "remaining_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 10,
            "elapsdT": 0,
            "id": 9,
            "initial_time": 0,
            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "56%20",
            "remaining_time_blocked": 0,
            "remaining_time_running": 10,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 18,
            "elapsdT": 0,
            "id": 10,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "25/100",
            "remaining_time_blocked": 0,
            "remaining_time_running": 18,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 18,
            "elapsdT": 0,
            "id": 11,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "89*78",
            "remaining_time_blocked": 0,
            "remaining_time_running": 18,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 14,
            "elapsdT": 0,
            "id": 12,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "47*96",
            "remaining_time_blocked": 0,
            "remaining_time_running": 14,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 10,
            "elapsdT": 0,
            "id": 13,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "1%31",
            "remaining_time_blocked": 0,
            "remaining_time_running": 10,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 14,
            "elapsdT": 0,
            "id": 14,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "66/91",
            "remaining_time_blocked": 0,
            "remaining_time_running": 14,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 7,
            "elapsdT": 0,
            "id": 15,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "47%98",
            "remaining_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 14,
            "elapsdT": 0,
            "id": 16,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "27/75",
            "remaining_time_blocked": 0,
            "remaining_time_running": 14,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 10,
            "elapsdT": 0,
            "id": 17,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "75/73",
            "remaining_time_blocked": 0,
            "remaining_time_running": 10,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 12,
            "elapsdT": 0,
            "id": 18,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "83%74",
            "remaining_time_blocked": 0,
            "remaining_time_running": 12,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 14,
            "elapsdT": 0,
            "id": 19,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "5+96",
            "remaining_time_blocked": 0,
            "remaining_time_running": 14,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 13,
            "elapsdT": 0,
            "id": 20,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "97-63",
            "remaining_time_blocked": 0,
            "remaining_time_running": 13,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 15,
            "elapsdT": 0,
            "id": 21,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "12*74",
            "remaining_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 5,
            "elapsdT": 0,
            "id": 22,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "86-73",
            "remaining_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 15,
            "elapsdT": 0,
            "id": 23,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "35-15",
            "remaining_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 17,
            "elapsdT": 0,
            "id": 24,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "6*54",
            "remaining_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 15,
            "elapsdT": 0,
            "id": 25,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "1*30",
            "remaining_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 10,
            "elapsdT": 0,
            "id": 26,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "20+34",
            "remaining_time_blocked": 0,
            "remaining_time_running": 10,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 13,
            "elapsdT": 0,
            "id": 27,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "86*19",
            "remaining_time_blocked": 0,
            "remaining_time_running": 13,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 10,
            "elapsdT": 0,
            "id": 28,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "69-69",
            "remaining_time_blocked": 0,
            "remaining_time_running": 10,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 17,
            "elapsdT": 0,
            "id": 29,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "1*88",
            "remaining_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        },
        {
            "TEM": 17,
            "elapsdT": 0,
            "id": 30,
            "initial_time": 0,

            "wait_time":0,
            "service_time":0,
            "is_finished": false,
            "operation": "92/72",
            "remaining_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "time_finished": 0,
            "time_blocked": 0,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "return_time": 0
        }
    ]