import {IProcess} from "../interfaces/ProcessRequest.ts";

export const processesData: IProcess[] =
    [

        {
            "TEM": 18,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "4a1a5c05-13ff-4834-ac73-c449caca0e6a",
            "initial_time": 0,
            "is_finished": false,
            "operation": "29*57",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 18,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "2ae4030f-f00f-48fe-b35b-790e9545d4eb",
            "initial_time": 0,
            "is_finished": false,
            "operation": "97-79",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 11,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "97d8789d-c4d4-49c0-bf8b-878c4757007e",
            "initial_time": 0,
            "is_finished": false,
            "operation": "87/70",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 11,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 11,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "bba9254a-995e-4be5-beae-f7a359741f9f",
            "initial_time": 0,
            "is_finished": false,
            "operation": "80-29",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 11,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 12,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "e4859788-f484-4be4-bedb-60174a1cb594",
            "initial_time": 0,
            "is_finished": false,
            "operation": "45/70",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 12,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "bf630949-ea5e-4375-bc9a-4b42f0890010",
            "initial_time": 0,
            "is_finished": false,
            "operation": "46%3",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "6e5e0c35-00a9-4c5e-9bf7-5c70b2fa759e",
            "initial_time": 0,
            "is_finished": false,
            "operation": "80*11",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 14,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "9b1edd59-29e9-4df1-bbca-bf27cbff5e4e",
            "initial_time": 0,
            "is_finished": false,
            "operation": "35-72",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 14,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 8,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "87abbc9a-d198-4e49-b88c-4a6f8bdc83cf",
            "initial_time": 0,
            "is_finished": false,
            "operation": "73/77",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 8,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 5,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "517b61ef-c78f-4bde-ad2d-73ddb171d21a",
            "initial_time": 0,
            "is_finished": false,
            "operation": "92-46",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 9,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "b89747db-6791-4d5b-8897-f4c683c6b725",
            "initial_time": 0,
            "is_finished": false,
            "operation": "47/81",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 9,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 12,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "96ef111e-eee8-4137-9389-6e4e2606c9d4",
            "initial_time": 0,
            "is_finished": false,
            "operation": "10/50",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 12,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 9,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "1ce8301a-ae21-4532-aea0-c05aed98736a",
            "initial_time": 0,
            "is_finished": false,
            "operation": "54%27",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 9,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 6,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "29d0eafe-89c0-4462-8592-6144d39bccae",
            "initial_time": 0,
            "is_finished": false,
            "operation": "44*9",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 6,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "eead979c-91f0-4c4b-8324-613727abfcf0",
            "initial_time": 0,
            "is_finished": false,
            "operation": "25+52",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 5,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "461659bf-1d62-43e9-a09f-e2e39f2c33b8",
            "initial_time": 0,
            "is_finished": false,
            "operation": "23+76",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 8,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "db819e75-5bc9-4276-a06b-d72f8a139b5a",
            "initial_time": 0,
            "is_finished": false,
            "operation": "50+5",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 8,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 16,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "90514cf2-6cd4-48af-9997-3607174d04f9",
            "initial_time": 0,
            "is_finished": false,
            "operation": "80/81",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 16,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 6,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "aff20405-74d8-4b5f-9aaf-a82a53322849",
            "initial_time": 0,
            "is_finished": false,
            "operation": "79*1",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 6,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 8,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "83b97678-b7f4-4e29-8751-499205121f58",
            "initial_time": 0,
            "is_finished": false,
            "operation": "93+24",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 8,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 18,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "21cd049b-665e-4214-a7a2-87ca9cc436cb",
            "initial_time": 0,
            "is_finished": false,
            "operation": "81/68",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 18,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "d2c7cb3b-c874-4358-a57b-5572b927599c",
            "initial_time": 0,
            "is_finished": false,
            "operation": "9+16",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 9,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "935e94cd-555c-4f8f-8859-f21ca720d721",
            "initial_time": 0,
            "is_finished": false,
            "operation": "18*86",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 9,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 18,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "a1ddb688-9e7a-48c9-8afc-5eefa5988f54",
            "initial_time": 0,
            "is_finished": false,
            "operation": "98%21",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 18,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 8,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "ce0c8413-c439-425a-b5e5-be299025a343",
            "initial_time": 0,
            "is_finished": false,
            "operation": "78%20",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 8,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 5,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "324f3dc5-631e-40eb-8706-4972cec05656",
            "initial_time": 0,
            "is_finished": false,
            "operation": "65-10",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 17,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "8ef234ca-a250-4fb0-87c1-d978e3ffe2bc",
            "initial_time": 0,
            "is_finished": false,
            "operation": "35%67",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 5,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "82c2333f-4528-4079-961b-0d74f6b59c2e",
            "initial_time": 0,
            "is_finished": false,
            "operation": "75-45",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 6,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "de55e20f-e73b-427f-b2f1-07adf9656bea",
            "initial_time": 0,
            "is_finished": false,
            "operation": "15-79",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 6,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "b1bad796-04a2-43ca-b017-b9db8cb2a81b",
            "initial_time": 0,
            "is_finished": false,
            "operation": "70-9",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 17,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "2279badc-ca19-45cf-88c1-32ae409f120b",
            "initial_time": 0,
            "is_finished": false,
            "operation": "22%99",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 6,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "8a209ae2-2906-44ee-a7a1-ef1853874803",
            "initial_time": 0,
            "is_finished": false,
            "operation": "78/44",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 6,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 15,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "5de050f6-17cf-4354-baf5-a8526e2aab82",
            "initial_time": 0,
            "is_finished": false,
            "operation": "43+5",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 11,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "358c4fdc-2044-4ac9-ae01-4d60b9998940",
            "initial_time": 0,
            "is_finished": false,
            "operation": "96%21",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 11,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 11,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "a1115a77-8f8b-4aab-be90-02c51cf3fdc7",
            "initial_time": 0,
            "is_finished": false,
            "operation": "98*44",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 11,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 6,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "b0320048-0ea1-4779-9907-14d1f9320567",
            "initial_time": 0,
            "is_finished": false,
            "operation": "49%34",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 6,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 5,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "ab5550c9-c921-4ada-85f4-cf90e8a37267",
            "initial_time": 0,
            "is_finished": false,
            "operation": "16*46",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 5,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "61f1d098-a75e-4111-9a19-51e775cbd55c",
            "initial_time": 0,
            "is_finished": false,
            "operation": "71/8",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 5,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 17,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "4e30b7ff-4435-443e-910b-131bf9793952",
            "initial_time": 0,
            "is_finished": false,
            "operation": "39/84",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 15,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "a248d037-5449-4ee4-bfa6-53fc51938383",
            "initial_time": 0,
            "is_finished": false,
            "operation": "61-66",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 8,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "a869df67-2b78-45dd-90c0-2629e2bb2dec",
            "initial_time": 0,
            "is_finished": false,
            "operation": "72%53",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 8,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 15,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "a36f2f86-8d5c-42c0-bd8d-4f4db8a17fd3",
            "initial_time": 0,
            "is_finished": false,
            "operation": "31*60",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 15,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 16,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "bb58fcf6-bdb1-46d3-8389-63c8eaf11eff",
            "initial_time": 0,
            "is_finished": false,
            "operation": "56%10",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 16,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 7,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "98fa4f86-772d-4b85-8295-05ac3aa97cd3",
            "initial_time": 0,
            "is_finished": false,
            "operation": "67+10",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 7,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 10,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "f58c97cf-7115-4dee-b949-accea04dfe14",
            "initial_time": 0,
            "is_finished": false,
            "operation": "58*64",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 10,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 16,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "2fb2eabb-d4d2-470a-b9be-a8d3a57d127a",
            "initial_time": 0,
            "is_finished": false,
            "operation": "97/7",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 16,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 18,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "b3b0f8cf-e7dc-43cb-81c7-0eedc24a96dc",
            "initial_time": 0,
            "is_finished": false,
            "operation": "38-59",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 18,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 12,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "560d6f28-156c-41fc-9e8e-2d4a3ff96d37",
            "initial_time": 0,
            "is_finished": false,
            "operation": "46%21",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 12,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 17,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "235bc0c4-0384-4a4e-a5af-f38960bebc8b",
            "initial_time": 0,
            "is_finished": false,
            "operation": "1%48",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 17,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        },
        {
            "TEM": 9,
            "addedToReadyForFirstTime": false,
            "addedToRunningProcessForFirstTime": false,
            "elapsdT": 0,
            "id": "f6f66a89-db66-47e7-90ee-8060b4621f73",
            "initial_time": 0,
            "is_finished": false,
            "operation": "75*91",
            "elapsed_time_blocked": 0,
            "remaining_time_running": 9,
            "response_time": 0,
            "return_time": 0,
            "service_time": 0,
            "state": "queue",
            "time_blocked": 0,
            "time_finished": 0,
            "wait_time": 0
        }

    ]
